#ifndef FLEX_HEADER_scanner_h
#define FLEX_HEADER_scanner_h
#define YY_CalcScanner_CHAR unsigned char
#line 1 "/usr/lib/flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#ifdef __cplusplus
#include <cstdio>
#else
#include <stdio.h>
#endif




/* % here is the declaration from section1 %header{  */ 
#line 2 "scanner.l"
#define YY_CalcScanner_LEX_PARAM  YY_CalcParser_STYPE *val, YY_CalcParser_LTYPE *loc
#line 3 "scanner.l"
#define YY_CalcScanner_MEMBERS  public: int line, column;
#line 4 "scanner.l"
#define YY_CalcScanner_CONSTRUCTOR_INIT  : line(1), column(1)
#line 7 "scanner.l"
#include "parser.h"


#define YY_INPUT(buf,result,max_size)           \
    {                                           \
        int c = getchar();                      \
        result = (c == EOF || c == '\n') ? YY_NULL : (buf[0] = c, 1);      \
    }
#line 17 "scanner.l"
#line 56 "/usr/lib/flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_CalcScanner_IOSTREAM
#include <iostream>
#define YY_CalcScanner_IFILE  std::istream
#define YY_CalcScanner_OFILE std::ostream 
#define YY_CalcScanner_ERRFILE std::cerr

#ifndef YY_CalcScanner_IFILE_DEFAULT
#define YY_CalcScanner_IFILE_DEFAULT &std::cin
#endif

#ifndef YY_CalcScanner_OFILE_DEFAULT
#define YY_CalcScanner_OFILE_DEFAULT &std::cout
#endif

#endif
#endif

#ifndef YY_CalcScanner_IFILE
#define YY_CalcScanner_IFILE FILE 
#endif

#ifndef YY_CalcScanner_OFILE
#define YY_CalcScanner_OFILE FILE 
#endif

#ifndef YY_CalcScanner_ERRFILE
#define YY_CalcScanner_ERRFILE stderr
#endif

#ifndef YY_CalcScanner_IFILE_DEFAULT
#define YY_CalcScanner_IFILE_DEFAULT stdin
#endif

#ifndef YY_CalcScanner_OFILE_DEFAULT
#define YY_CalcScanner_OFILE_DEFAULT stdout
#endif




#ifndef YY_CalcScanner_TEXT
#define YY_CalcScanner_TEXT yytext
#endif
#ifndef YY_CalcScanner_LENG
#define YY_CalcScanner_LENG yyleng
#endif
#ifndef YY_CalcScanner_IN
#define YY_CalcScanner_IN yyin
#endif
#ifndef YY_CalcScanner_OUT
#define YY_CalcScanner_OUT yyout
#endif

#ifndef YY_CalcScanner_LEX_RETURN
#define YY_CalcScanner_LEX_RETURN int
#else
#ifndef YY_CalcScanner_LEX_DEFINED
#define YY_CalcScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_CalcScanner_LEX
#define YY_CalcScanner_LEX yylex
#else
#ifndef YY_CalcScanner_LEX_DEFINED
#define YY_CalcScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_CalcScanner_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_CalcScanner_LEX_PARAM 
#else
#define YY_CalcScanner_LEX_PARAM void
#endif
#else
#ifndef YY_CalcScanner_LEX_DEFINED
#define YY_CalcScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_CalcScanner_LEX_PARAM_DEF
#define YY_CalcScanner_LEX_PARAM_DEF
#else
#ifndef YY_CalcScanner_LEX_DEFINED
#define YY_CalcScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_CalcScanner_RESTART
#define YY_CalcScanner_RESTART yyrestart
#endif
#ifndef YY_CalcScanner_SWITCH_TO_BUFFER
#define YY_CalcScanner_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_CalcScanner_LOAD_BUFFER_STATE
#define YY_CalcScanner_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_CalcScanner_CREATE_BUFFER
#define YY_CalcScanner_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_CalcScanner_DELETE_BUFFER
#define YY_CalcScanner_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_CalcScanner_INIT_BUFFER
#define YY_CalcScanner_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_CalcScanner_FLEX_DEBUG
#ifndef YY_CalcScanner_DEBUG
#define YY_CalcScanner_DEBUG 1
#endif
#else
#ifndef YY_CalcScanner_DEBUG
#define YY_CalcScanner_DEBUG 0
#endif
#endif

#if YY_CalcScanner_DEBUG != 0
#ifndef YY_CalcScanner_DEBUG_FLAG
#define YY_CalcScanner_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_CalcScanner_DEBUG_INIT
#define YY_CalcScanner_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_CalcScanner_CURRENT_BUFFER
#define YY_CalcScanner_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_CalcScanner_RESTART YY_PROTO(( YY_CalcScanner_IFILE *input_file ));
extern void YY_CalcScanner_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_CalcScanner_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_CalcScanner_CREATE_BUFFER YY_PROTO(( YY_CalcScanner_IFILE *file, int size ));
extern void YY_CalcScanner_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_CalcScanner_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_CalcScanner_IFILE *file ));

#if YY_CalcScanner_DEBUG != 0
extern int YY_CalcScanner_DEBUG_FLAG ;
#endif
extern YY_CalcScanner_CHAR  *YY_CalcScanner_TEXT;
extern int YY_CalcScanner_LENG;
extern YY_CalcScanner_IFILE *YY_CalcScanner_IN;
extern YY_CalcScanner_OFILE *YY_CalcScanner_OUT;
#ifdef YY_CalcScanner_LEX_DEFINED
extern YY_CalcScanner_LEX_RETURN YY_CalcScanner_LEX ( YY_CalcScanner_LEX_PARAM )
YY_CalcScanner_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_CalcScanner_LEX_RETURN YY_CalcScanner_LEX ( YY_CalcScanner_LEX_PARAM )
YY_CalcScanner_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_CalcScanner_CURRENT_BUFFER
#define YY_CalcScanner_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_CalcScanner_CLASS
#define YY_CalcScanner_CLASS CalcScanner
#endif
#ifndef YY_CalcScanner_ECHO
#define YY_CalcScanner_ECHO yy_echo
#endif
#ifdef YY_CalcScanner_ECHO_PURE
#define YY_CalcScanner_ECHO_NOCODE
#endif

#ifndef YY_CalcScanner_ECHO_CODE
#ifndef YY_CalcScanner_IOSTREAM
#define YY_CalcScanner_ECHO_CODE fwrite( (char *) YY_CalcScanner_TEXT, YY_CalcScanner_LENG, 1, YY_CalcScanner_OUT );
#else
#define YY_CalcScanner_ECHO_CODE (YY_CalcScanner_OUT->write( (char *) YY_CalcScanner_TEXT, YY_CalcScanner_LENG));
#endif
#endif

#ifndef YY_CalcScanner_INPUT
#define YY_CalcScanner_INPUT yy_input
#endif
#ifdef YY_CalcScanner_INPUT_PURE
#define YY_CalcScanner_INPUT_NOCODE
#endif

#ifndef YY_CalcScanner_INPUT_CODE
#ifndef YY_CalcScanner_IOSTREAM
#define YY_CalcScanner_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_CalcScanner_IN );
#else
#define YY_CalcScanner_INPUT_CODE if(YY_CalcScanner_IN->eof())  result=0;else {YY_CalcScanner_IN->read(buffer,max_size);result=YY_CalcScanner_IN->gcount();YY_CalcScanner_IN->clear(YY_CalcScanner_IN->rdstate()&(~std::ios::failbit));if(YY_CalcScanner_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_CalcScanner_FATAL_ERROR_PURE
#define YY_CalcScanner_FATAL_ERRO_NOCODE
#endif
#ifndef YY_CalcScanner_FATAL_ERROR
#define YY_CalcScanner_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_CalcScanner_FATAL_ERROR_CODE
#ifndef YY_CalcScanner_IOSTREAM
#define YY_CalcScanner_FATAL_ERROR_CODE fputs( msg, YY_CalcScanner_ERRFILE );putc( '\n', YY_CalcScanner_ERRFILE );exit( 1 );
#else
#define YY_CalcScanner_FATAL_ERROR_CODE YY_CalcScanner_ERRFILE<< msg <<std::endl;exit( 1 );
#endif
#endif

#ifndef YY_CalcScanner_WRAP
#define YY_CalcScanner_WRAP yy_wrap
#endif
#ifdef YY_CalcScanner_WRAP_PURE
#define YY_CalcScanner_WRAP_NOCODE
#endif
#ifndef YY_CalcScanner_WRAP_CODE
#define YY_CalcScanner_WRAP_CODE return 1;
#endif


#ifndef YY_CalcScanner_INHERIT
#define YY_CalcScanner_INHERIT
#endif
#ifndef YY_CalcScanner_MEMBERS
#define YY_CalcScanner_MEMBERS 
#endif
#ifndef YY_CalcScanner_CONSTRUCTOR_PARAM
#define YY_CalcScanner_CONSTRUCTOR_PARAM
#endif
#ifndef YY_CalcScanner_CONSTRUCTOR_CODE
#define YY_CalcScanner_CONSTRUCTOR_CODE
#endif
#ifndef YY_CalcScanner_CONSTRUCTOR_INIT
#define YY_CalcScanner_CONSTRUCTOR_INIT
#endif
#ifndef YY_CalcScanner_DESTRUCTOR_CODE
#define YY_CalcScanner_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_CalcScanner_CLASS YY_CalcScanner_INHERIT
{
 private:/* data */
 YY_CalcScanner_CHAR  *yy_c_buf_p;
 YY_CalcScanner_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_CalcScanner_CHAR  c, YY_CalcScanner_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_CalcScanner_CURRENT_BUFFER;
 void YY_CalcScanner_RESTART ( YY_CalcScanner_IFILE *input_file );
 void YY_CalcScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_CalcScanner_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_CalcScanner_CREATE_BUFFER( YY_CalcScanner_IFILE *file, int size );
 void YY_CalcScanner_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_CalcScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_CalcScanner_IFILE *file );
 protected: /* virtual */
 virtual void YY_CalcScanner_ECHO()
#ifdef YY_CalcScanner_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_CalcScanner_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_CalcScanner_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_CalcScanner_FATAL_ERROR(const char *msg)
#ifdef YY_CalcScanner_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_CalcScanner_WRAP()
#ifdef YY_CalcScanner_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_CalcScanner_CHAR  *YY_CalcScanner_TEXT;
 int YY_CalcScanner_LENG;
 YY_CalcScanner_IFILE *YY_CalcScanner_IN;
 YY_CalcScanner_OFILE *YY_CalcScanner_OUT;
 YY_CalcScanner_LEX_RETURN YY_CalcScanner_LEX ( YY_CalcScanner_LEX_PARAM);
 YY_CalcScanner_CLASS(YY_CalcScanner_CONSTRUCTOR_PARAM) ;
 virtual ~YY_CalcScanner_CLASS() ;
#if YY_CalcScanner_DEBUG != 0
 int YY_CalcScanner_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_CalcScanner_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 60 "scanner.l"
#endif
#line 379 "/usr/lib/flexskel.h"

/* end of generated header */
